//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Doker
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Город.
    /// </summary>
    // *** Start programmer edit section *** (Город CustomAttributes)

    // *** End programmer edit section *** (Город CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГородE", new string[] {
            "Имя as \'Имя\'"})]
    [View("ГородL", new string[] {
            "Имя as \'Имя\'"})]
    public class Город : ICSSoft.STORMNET.DataObject
    {
        
        private string fИмя;
        
        // *** Start programmer edit section *** (Город CustomMembers)

        // *** End programmer edit section *** (Город CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Город.Имя CustomAttributes)

        // *** End programmer edit section *** (Город.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Город.Имя Get start)

                // *** End programmer edit section *** (Город.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Город.Имя Get end)

                // *** End programmer edit section *** (Город.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Город.Имя Set start)

                // *** End programmer edit section *** (Город.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Город.Имя Set end)

                // *** End programmer edit section *** (Город.Имя Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГородE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГородE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГородE", typeof(IIS.Doker.Город));
                }
            }
            
            /// <summary>
            /// "ГородL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГородL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГородL", typeof(IIS.Doker.Город));
                }
            }
        }
    }
}
