//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Doker
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Здание.
    /// </summary>
    // *** Start programmer edit section *** (Здание CustomAttributes)

    // *** End programmer edit section *** (Здание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗданиеE", new string[] {
            "Адрем as \'Адрем\'",
            "Этажи as \'Этажи\'",
            "Город as \'Город\'",
            "Город.Имя as \'Имя\'"}, Hidden=new string[] {
            "Город.Имя"})]
    [MasterViewDefineAttribute("ЗданиеE", "Город", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    [View("ЗданиеL", new string[] {
            "Адрем as \'Адрем\'",
            "Этажи as \'Этажи\'",
            "Город.Имя as \'Имя\'"})]
    public class Здание : ICSSoft.STORMNET.DataObject
    {
        
        private string fАдрем;
        
        private int fЭтажи;
        
        private IIS.Doker.Город fГород;
        
        // *** Start programmer edit section *** (Здание CustomMembers)

        // *** End programmer edit section *** (Здание CustomMembers)

        
        /// <summary>
        /// Адрем.
        /// </summary>
        // *** Start programmer edit section *** (Здание.Адрем CustomAttributes)

        // *** End programmer edit section *** (Здание.Адрем CustomAttributes)
        [StrLen(255)]
        public virtual string Адрем
        {
            get
            {
                // *** Start programmer edit section *** (Здание.Адрем Get start)

                // *** End programmer edit section *** (Здание.Адрем Get start)
                string result = this.fАдрем;
                // *** Start programmer edit section *** (Здание.Адрем Get end)

                // *** End programmer edit section *** (Здание.Адрем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.Адрем Set start)

                // *** End programmer edit section *** (Здание.Адрем Set start)
                this.fАдрем = value;
                // *** Start programmer edit section *** (Здание.Адрем Set end)

                // *** End programmer edit section *** (Здание.Адрем Set end)
            }
        }
        
        /// <summary>
        /// Этажи.
        /// </summary>
        // *** Start programmer edit section *** (Здание.Этажи CustomAttributes)

        // *** End programmer edit section *** (Здание.Этажи CustomAttributes)
        public virtual int Этажи
        {
            get
            {
                // *** Start programmer edit section *** (Здание.Этажи Get start)

                // *** End programmer edit section *** (Здание.Этажи Get start)
                int result = this.fЭтажи;
                // *** Start programmer edit section *** (Здание.Этажи Get end)

                // *** End programmer edit section *** (Здание.Этажи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.Этажи Set start)

                // *** End programmer edit section *** (Здание.Этажи Set start)
                this.fЭтажи = value;
                // *** Start programmer edit section *** (Здание.Этажи Set end)

                // *** End programmer edit section *** (Здание.Этажи Set end)
            }
        }
        
        /// <summary>
        /// Здание.
        /// </summary>
        // *** Start programmer edit section *** (Здание.Город CustomAttributes)

        // *** End programmer edit section *** (Здание.Город CustomAttributes)
        [PropertyStorage(new string[] {
                "Город"})]
        [NotNull()]
        public virtual IIS.Doker.Город Город
        {
            get
            {
                // *** Start programmer edit section *** (Здание.Город Get start)

                // *** End programmer edit section *** (Здание.Город Get start)
                IIS.Doker.Город result = this.fГород;
                // *** Start programmer edit section *** (Здание.Город Get end)

                // *** End programmer edit section *** (Здание.Город Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.Город Set start)

                // *** End programmer edit section *** (Здание.Город Set start)
                this.fГород = value;
                // *** Start programmer edit section *** (Здание.Город Set end)

                // *** End programmer edit section *** (Здание.Город Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗданиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗданиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗданиеE", typeof(IIS.Doker.Здание));
                }
            }
            
            /// <summary>
            /// "ЗданиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗданиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗданиеL", typeof(IIS.Doker.Здание));
                }
            }
        }
    }
}
